#!/usr/bin/python3.6
from pprint import pprint

with open("show_vlan.txt") as f:
    output = f.read()

vlan_list = [] 

for line in output.splitlines(): 
    ## Skip header lines
    if "VLAN" in line or "---" in line or line.startswith("        "):
        continue
    fields = line.split()
    #print(fields)
    vlan_id = fields[0]
    vlan_name = fields[1] 
    vlan_list.append((vlan_id, vlan_name))

pprint(vlan_list)



## Below is wrong but useful for future notes
#i = 0
#while True:
#    i += 1
#    if i > len(output):
#        break
#    for vlan_id in output:
        


