#!/usr/bin/python3.6
from pprint import pprint

with open("show_arp.txt") as f:
    output = f.read()

tracker1, tracker2 = (False, False)
for line in output.splitlines():
    if "Protocol" in line:
        continue
    line = line.split()
    ip_addr = line[1]
    mac_addr = line[3]

    #print("IP: {}\nMAC: {}\n".format(ip_addr, mac_addr))
    ## Check for default gateway and print
    if "10.220.88.1" in line:
        print("-" *10)
        print("Default gateway IP/Mac: {} {}".format(ip_addr, mac_addr))
        print("-" *10, "\n")
        tracker1 = True

    ## Check for Arista3 IP and print
    if "10.220.88.30" in line:
        print("-" *10)
        print("Arista3 IP/Mac is: {} {}".format(ip_addr, mac_addr))
        print("-" *10, "\n")
        tracker2 = True

    if tracker1 and tracker2 == True:
        break